# Generated by Django 3.1.4 on 2021-05-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourdiary', '0009_auto_20210519_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userparams',
            name='avatar',
            field=models.ImageField(default='users_avatars/default_avatar.png', upload_to='users_avatars/'),
        ),
    ]
